### ISSUE TITLE
Test CASAS ADL Normal detection rules

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#55]
### Why
To test the utility of the CONSERT Engine implemented over DROOLS capabilities we decided to study the efficiency in detecting the set of activities defined in the CASAS ADL Normal dataset.

ContextEntity, ContextAssertions as well as rules that utilize the latter have been defined to detect each of the 5 ADL categories contained within the CASAS ADL Normal dataset.

The correctness of these rules now needs to be tested.

### What
  - [x] missing ContextAssertion and ContextEntities are implemented
  - [x] the rules are inspected and validated to detect the expected activity category
  - [x] follow-up issues included in this epic are filed to investigate and solve bugs/errors that appear during testing
