### ISSUE TITLE
High-Level Activity recognition scenario over Drools Fusion

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#9]
### Why
In order to test the time interval logic and temporal validity extension capabilities of Drools Fusion, we need a workable scenario which has been used in the past with the same intent.
We therefore implement a demo Drools project  of the AmI-Lab High-Level Activity (HLA) recognition example, to server as basis for all CONSERT Engine improvement tasks.

### What
 * [x] Drools specific classes are created for each event and entity type used in the AmI-Lab HLA example, along with the appropriate annotations
      - position
      - low-level activity (LLA)
      - WorkingHLA, DiscussingHLA, ExerciseHLA, etc
      - Person, Location entity types 
  * [x] A parser is created to read input events serialized in ETALIS format
  * [x] The HLA detection rules are modeled in Drools Rule Language
  * [x] Separate event streams are created for *atomic events* and the *interval events*
  * [x] The event temporal validity extension mechanism is implemented
